# Generated by Django 3.2.20 on 2023-08-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230805_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imange_filter',
            new_name='image_filter',
        ),
    ]
