# Generated by Django 3.2.20 on 2023-08-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_imange_filter_post_image_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='https://res.cloudinary.com/pjdevex/image/upload/v1691082053/django-rest/default_post_a4ly1s.jpg', upload_to='images/'),
        ),
    ]
