# Generated by Django 3.2.20 on 2023-08-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/pjdevex/image/upload/v1691082053/django-rest/default_profile_gj2yan.jpg', upload_to='images/'),
        ),
    ]
